# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'JWBleDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	
   pod 'Masonry'
   pod 'FMDB'
   pod 'libxlsxwriter'

#   pod 'MJRefresh'

  # Pods for JWBleDemo

end
